version: '3.8'

services:
  swagger-ui-local:
    image: "swaggerapi/swagger-ui:latest"
    container_name: swagger-ui-local
    ports:
      - "8080:8080"
    environment:
      - BASE_URL=/api/docs
      - SWAGGER_JSON=/app/swagger.json
    volumes:
      - "./docker/swagger:/app"
