service: vuttr-rest-api
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-offline

custom:
  dynamoDbTableName: ${param:table_name, 'tools'}
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3001
    printOutput: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  # httpApi:
  #   cors: true
  environment:
    AWS_DYNAMODB_TABLE_NAME: ${self:service}-${self:provider.stage}-${self:custom.dynamoDbTableName}
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        # padrão: arn:aws:dynamodb:{region}:{account-id}:table/{table-name}
        # fonte: https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#arn-syntax-ddb
        Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.AWS_DYNAMODB_TABLE_NAME}"

functions:
  saveTool:
    handler: dist/main.handler
    events:
      - httpApi:
          path: /api/tools
          method: POST
  deleteTool:
    handler: dist/main.handler
    events:
      - httpApi:
          path: /api/tools/{id}
          method: DELETE
  getTool:
    handler: dist/main.handler
    events:
      - httpApi:
          path: /api/tools/{id}
          method: GET
  getTools:
    handler: dist/main.handler
    events:
      - httpApi:
          path: /api/tools
          method: GET
  partialToolUpdate:
    handler: dist/main.handler
    events:
      - httpApi:
          path: /api/tools/{id}
          method: PATCH
  default:
    handler: dist/main.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    toolsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.AWS_DYNAMODB_TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S

